/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 36.7.0 Wed Jan 11 12:04:43 2023.
 */

#include <string.h>

#include "ke20_bms.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int bms_bms_power_prediction_pack(
    uint8_t *dst_p,
    const struct bms_bms_power_prediction_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->regen_current_pred_bms, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->regen_current_pred_bms, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->discharge_current_pred_bms, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->discharge_current_pred_bms, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->regen_power_pred_bms, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->regen_power_pred_bms, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->discharge_power_pred_bms, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->discharge_power_pred_bms, 0u, 0xffu);

    return (8);
}

int bms_bms_power_prediction_unpack(
    struct bms_bms_power_prediction_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->regen_current_pred_bms = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->regen_current_pred_bms |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->discharge_current_pred_bms = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->discharge_current_pred_bms |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->regen_power_pred_bms = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->regen_power_pred_bms |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->discharge_power_pred_bms = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->discharge_power_pred_bms |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

uint16_t bms_bms_power_prediction_regen_current_pred_bms_encode(double value)
{
    return (uint16_t)(value / 0.05);
}

double bms_bms_power_prediction_regen_current_pred_bms_decode(uint16_t value)
{
    return ((double)value * 0.05);
}

bool bms_bms_power_prediction_regen_current_pred_bms_is_in_range(uint16_t value)
{
    return (value <= 64000u);
}

uint16_t bms_bms_power_prediction_discharge_current_pred_bms_encode(double value)
{
    return (uint16_t)(value / 0.05);
}

double bms_bms_power_prediction_discharge_current_pred_bms_decode(uint16_t value)
{
    return ((double)value * 0.05);
}

bool bms_bms_power_prediction_discharge_current_pred_bms_is_in_range(uint16_t value)
{
    return (value <= 64000u);
}

uint16_t bms_bms_power_prediction_regen_power_pred_bms_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double bms_bms_power_prediction_regen_power_pred_bms_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool bms_bms_power_prediction_regen_power_pred_bms_is_in_range(uint16_t value)
{
    return (value <= 65000u);
}

uint16_t bms_bms_power_prediction_discharge_power_pred_bms_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double bms_bms_power_prediction_discharge_power_pred_bms_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool bms_bms_power_prediction_discharge_power_pred_bms_is_in_range(uint16_t value)
{
    return (value <= 65000u);
}

int bms_bms_fluid_meas_user_soc_pack(
    uint8_t *dst_p,
    const struct bms_bms_fluid_meas_user_soc_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->fluid_temperature_inlet_bms, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->fluid_temperature_outlet_bms, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->user_soc_bms, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->user_soc_bms, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->fluid_pressure_inlet_bms, 0u, 0xffu);

    return (8);
}

int bms_bms_fluid_meas_user_soc_unpack(
    struct bms_bms_fluid_meas_user_soc_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fluid_temperature_inlet_bms = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->fluid_temperature_outlet_bms = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->user_soc_bms = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->user_soc_bms |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->fluid_pressure_inlet_bms = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

uint8_t bms_bms_fluid_meas_user_soc_fluid_temperature_inlet_bms_encode(double value)
{
    return (uint8_t)((value - -40.0) / 0.5);
}

double bms_bms_fluid_meas_user_soc_fluid_temperature_inlet_bms_decode(uint8_t value)
{
    return (((double)value * 0.5) + -40.0);
}

bool bms_bms_fluid_meas_user_soc_fluid_temperature_inlet_bms_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

uint8_t bms_bms_fluid_meas_user_soc_fluid_temperature_outlet_bms_encode(double value)
{
    return (uint8_t)((value - -40.0) / 0.5);
}

double bms_bms_fluid_meas_user_soc_fluid_temperature_outlet_bms_decode(uint8_t value)
{
    return (((double)value * 0.5) + -40.0);
}

bool bms_bms_fluid_meas_user_soc_fluid_temperature_outlet_bms_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

uint16_t bms_bms_fluid_meas_user_soc_user_soc_bms_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double bms_bms_fluid_meas_user_soc_user_soc_bms_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool bms_bms_fluid_meas_user_soc_user_soc_bms_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

uint8_t bms_bms_fluid_meas_user_soc_fluid_pressure_inlet_bms_encode(double value)
{
    return (uint8_t)(value / 10.0);
}

double bms_bms_fluid_meas_user_soc_fluid_pressure_inlet_bms_decode(uint8_t value)
{
    return ((double)value * 10.0);
}

bool bms_bms_fluid_meas_user_soc_fluid_pressure_inlet_bms_is_in_range(uint8_t value)
{
    return (value <= 254u);
}

int bms_bms_string_voltages_pack(
    uint8_t *dst_p,
    const struct bms_bms_string_voltages_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->min_string_voltage_bms, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->min_string_voltage_bms, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->max_string_voltage_bms, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->max_string_voltage_bms, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->link_voltage_auxiliary1_bms, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->link_voltage_auxiliary1_bms, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->link_voltage_auxiliary2_bms, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->link_voltage_auxiliary2_bms, 0u, 0xffu);

    return (8);
}

int bms_bms_string_voltages_unpack(
    struct bms_bms_string_voltages_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->min_string_voltage_bms = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->min_string_voltage_bms |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->max_string_voltage_bms = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->max_string_voltage_bms |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->link_voltage_auxiliary1_bms = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->link_voltage_auxiliary1_bms |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->link_voltage_auxiliary2_bms = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->link_voltage_auxiliary2_bms |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

uint16_t bms_bms_string_voltages_min_string_voltage_bms_encode(double value)
{
    return (uint16_t)(value / 0.02);
}

double bms_bms_string_voltages_min_string_voltage_bms_decode(uint16_t value)
{
    return ((double)value * 0.02);
}

bool bms_bms_string_voltages_min_string_voltage_bms_is_in_range(uint16_t value)
{
    return (value <= 60000u);
}

uint16_t bms_bms_string_voltages_max_string_voltage_bms_encode(double value)
{
    return (uint16_t)(value / 0.02);
}

double bms_bms_string_voltages_max_string_voltage_bms_decode(uint16_t value)
{
    return ((double)value * 0.02);
}

bool bms_bms_string_voltages_max_string_voltage_bms_is_in_range(uint16_t value)
{
    return (value <= 60000u);
}

uint16_t bms_bms_string_voltages_link_voltage_auxiliary1_bms_encode(double value)
{
    return (uint16_t)(value / 0.02);
}

double bms_bms_string_voltages_link_voltage_auxiliary1_bms_decode(uint16_t value)
{
    return ((double)value * 0.02);
}

bool bms_bms_string_voltages_link_voltage_auxiliary1_bms_is_in_range(uint16_t value)
{
    return (value <= 60000u);
}

uint16_t bms_bms_string_voltages_link_voltage_auxiliary2_bms_encode(double value)
{
    return (uint16_t)(value / 0.02);
}

double bms_bms_string_voltages_link_voltage_auxiliary2_bms_decode(uint16_t value)
{
    return ((double)value * 0.02);
}

bool bms_bms_string_voltages_link_voltage_auxiliary2_bms_is_in_range(uint16_t value)
{
    return (value <= 60000u);
}

int bms_bms_module_temperatures_pack(
    uint8_t *dst_p,
    const struct bms_bms_module_temperatures_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->min_module_temperature_bms, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->max_module_temperature_bms, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->min_module_temperature_index_bms, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->min_module_temperature_index_bms, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->max_module_temperature_index_bms, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->max_module_temperature_index_bms, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->max_dew_point_temperature_bms, 0u, 0xffu);

    return (7);
}

int bms_bms_module_temperatures_unpack(
    struct bms_bms_module_temperatures_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->min_module_temperature_bms = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->max_module_temperature_bms = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->min_module_temperature_index_bms = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->min_module_temperature_index_bms |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->max_module_temperature_index_bms = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->max_module_temperature_index_bms |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->max_dew_point_temperature_bms = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

uint8_t bms_bms_module_temperatures_min_module_temperature_bms_encode(double value)
{
    return (uint8_t)((value - -40.0) / 0.5);
}

double bms_bms_module_temperatures_min_module_temperature_bms_decode(uint8_t value)
{
    return (((double)value * 0.5) + -40.0);
}

bool bms_bms_module_temperatures_min_module_temperature_bms_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

uint8_t bms_bms_module_temperatures_max_module_temperature_bms_encode(double value)
{
    return (uint8_t)((value - -40.0) / 0.5);
}

double bms_bms_module_temperatures_max_module_temperature_bms_decode(uint8_t value)
{
    return (((double)value * 0.5) + -40.0);
}

bool bms_bms_module_temperatures_max_module_temperature_bms_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

uint16_t bms_bms_module_temperatures_min_module_temperature_index_bms_encode(double value)
{
    return (uint16_t)(value);
}

double bms_bms_module_temperatures_min_module_temperature_index_bms_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_bms_module_temperatures_min_module_temperature_index_bms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_bms_module_temperatures_max_module_temperature_index_bms_encode(double value)
{
    return (uint16_t)(value);
}

double bms_bms_module_temperatures_max_module_temperature_index_bms_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_bms_module_temperatures_max_module_temperature_index_bms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t bms_bms_module_temperatures_max_dew_point_temperature_bms_encode(double value)
{
    return (uint8_t)((value - -40.0) / 0.5);
}

double bms_bms_module_temperatures_max_dew_point_temperature_bms_decode(uint8_t value)
{
    return (((double)value * 0.5) + -40.0);
}

bool bms_bms_module_temperatures_max_dew_point_temperature_bms_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

int bms_sc01_state_pack(
    uint8_t *dst_p,
    const struct bms_sc01_state_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_right_shift_u16(src_p->link_voltage_sc01, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->link_voltage_sc01, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->emergency_request_sc01, 0u, 0x0fu);
    dst_p[3] |= pack_left_shift_u8(src_p->alive_sc01, 0u, 0x0fu);
    dst_p[4] |= pack_left_shift_u8(src_p->crc_sc01, 0u, 0xffu);

    return (5);
}

int bms_sc01_state_unpack(
    struct bms_sc01_state_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->link_voltage_sc01 = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->link_voltage_sc01 |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->emergency_request_sc01 = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->alive_sc01 = unpack_right_shift_u8(src_p[3], 0u, 0x0fu);
    dst_p->crc_sc01 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

uint16_t bms_sc01_state_link_voltage_sc01_encode(double value)
{
    return (uint16_t)((value - -1250.0) / 0.04);
}

double bms_sc01_state_link_voltage_sc01_decode(uint16_t value)
{
    return (((double)value * 0.04) + -1250.0);
}

bool bms_sc01_state_link_voltage_sc01_is_in_range(uint16_t value)
{
    return (value <= 62500u);
}

uint8_t bms_sc01_state_emergency_request_sc01_encode(double value)
{
    return (uint8_t)(value);
}

double bms_sc01_state_emergency_request_sc01_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_sc01_state_emergency_request_sc01_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t bms_sc01_state_alive_sc01_encode(double value)
{
    return (uint8_t)(value);
}

double bms_sc01_state_alive_sc01_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_sc01_state_alive_sc01_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t bms_sc01_state_crc_sc01_encode(double value)
{
    return (uint8_t)(value);
}

double bms_sc01_state_crc_sc01_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_sc01_state_crc_sc01_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int bms_bms_charge_pack(
    uint8_t *dst_p,
    const struct bms_bms_charge_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_right_shift_u16(src_p->charge_current_setpoint_bms, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->charge_current_setpoint_bms, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->charge_voltage_limit_bms, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->charge_voltage_limit_bms, 0u, 0xffu);

    return (4);
}

int bms_bms_charge_unpack(
    struct bms_bms_charge_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->charge_current_setpoint_bms = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->charge_current_setpoint_bms |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->charge_voltage_limit_bms = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->charge_voltage_limit_bms |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);

    return (0);
}

uint16_t bms_bms_charge_charge_current_setpoint_bms_encode(double value)
{
    return (uint16_t)(value / 0.05);
}

double bms_bms_charge_charge_current_setpoint_bms_decode(uint16_t value)
{
    return ((double)value * 0.05);
}

bool bms_bms_charge_charge_current_setpoint_bms_is_in_range(uint16_t value)
{
    return (value <= 64000u);
}

uint16_t bms_bms_charge_charge_voltage_limit_bms_encode(double value)
{
    return (uint16_t)(value / 0.02);
}

double bms_bms_charge_charge_voltage_limit_bms_decode(uint16_t value)
{
    return ((double)value * 0.02);
}

bool bms_bms_charge_charge_voltage_limit_bms_is_in_range(uint16_t value)
{
    return (value <= 60000u);
}

int bms_bms_isolation_soc_pack(
    uint8_t *dst_p,
    const struct bms_bms_isolation_soc_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->isolation_resistance_extern_bms, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->isolation_resistance_extern_bms, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->isolation_resistance_intern_bms, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->isolation_resistance_intern_bms, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->min_soc_bms, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->min_soc_bms, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->max_soc_bms, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->max_soc_bms, 0u, 0xffu);

    return (8);
}

int bms_bms_isolation_soc_unpack(
    struct bms_bms_isolation_soc_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->isolation_resistance_extern_bms = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->isolation_resistance_extern_bms |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->isolation_resistance_intern_bms = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->isolation_resistance_intern_bms |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->min_soc_bms = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->min_soc_bms |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->max_soc_bms = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->max_soc_bms |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

uint16_t bms_bms_isolation_soc_isolation_resistance_extern_bms_encode(double value)
{
    return (uint16_t)(value / 2.0);
}

double bms_bms_isolation_soc_isolation_resistance_extern_bms_decode(uint16_t value)
{
    return ((double)value * 2.0);
}

bool bms_bms_isolation_soc_isolation_resistance_extern_bms_is_in_range(uint16_t value)
{
    return (value <= 65000u);
}

uint16_t bms_bms_isolation_soc_isolation_resistance_intern_bms_encode(double value)
{
    return (uint16_t)(value / 2.0);
}

double bms_bms_isolation_soc_isolation_resistance_intern_bms_decode(uint16_t value)
{
    return ((double)value * 2.0);
}

bool bms_bms_isolation_soc_isolation_resistance_intern_bms_is_in_range(uint16_t value)
{
    return (value <= 65000u);
}

uint16_t bms_bms_isolation_soc_min_soc_bms_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double bms_bms_isolation_soc_min_soc_bms_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool bms_bms_isolation_soc_min_soc_bms_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

uint16_t bms_bms_isolation_soc_max_soc_bms_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double bms_bms_isolation_soc_max_soc_bms_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool bms_bms_isolation_soc_max_soc_bms_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

int bms_bms_energy_soh_pack(
    uint8_t *dst_p,
    const struct bms_bms_energy_soh_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->energy_available_bms, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->energy_available_bms, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->min_soh_bms, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->max_soh_bms, 0u, 0xffu);

    return (8);
}

int bms_bms_energy_soh_unpack(
    struct bms_bms_energy_soh_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->energy_available_bms = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->energy_available_bms |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->min_soh_bms = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->max_soh_bms = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

    return (0);
}

uint16_t bms_bms_energy_soh_energy_available_bms_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double bms_bms_energy_soh_energy_available_bms_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool bms_bms_energy_soh_energy_available_bms_is_in_range(uint16_t value)
{
    return (value <= 65000u);
}

uint8_t bms_bms_energy_soh_min_soh_bms_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double bms_bms_energy_soh_min_soh_bms_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool bms_bms_energy_soh_min_soh_bms_is_in_range(uint8_t value)
{
    return (value <= 240u);
}

uint8_t bms_bms_energy_soh_max_soh_bms_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double bms_bms_energy_soh_max_soh_bms_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool bms_bms_energy_soh_max_soh_bms_is_in_range(uint8_t value)
{
    return (value <= 240u);
}

int bms_bms_brick_voltages_pack(
    uint8_t *dst_p,
    const struct bms_bms_brick_voltages_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->min_brick_voltage_bms, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->min_brick_voltage_bms, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->max_brick_voltage_bms, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->max_brick_voltage_bms, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->min_brick_voltage_index_bms, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->min_brick_voltage_index_bms, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->max_brick_voltage_index_bms, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->max_brick_voltage_index_bms, 0u, 0xffu);

    return (8);
}

int bms_bms_brick_voltages_unpack(
    struct bms_bms_brick_voltages_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->min_brick_voltage_bms = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->min_brick_voltage_bms |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->max_brick_voltage_bms = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->max_brick_voltage_bms |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->min_brick_voltage_index_bms = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->min_brick_voltage_index_bms |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->max_brick_voltage_index_bms = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->max_brick_voltage_index_bms |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

uint16_t bms_bms_brick_voltages_min_brick_voltage_bms_encode(double value)
{
    return (uint16_t)(value / 0.0001);
}

double bms_bms_brick_voltages_min_brick_voltage_bms_decode(uint16_t value)
{
    return ((double)value * 0.0001);
}

bool bms_bms_brick_voltages_min_brick_voltage_bms_is_in_range(uint16_t value)
{
    return (value <= 65000u);
}

uint16_t bms_bms_brick_voltages_max_brick_voltage_bms_encode(double value)
{
    return (uint16_t)(value / 0.0001);
}

double bms_bms_brick_voltages_max_brick_voltage_bms_decode(uint16_t value)
{
    return ((double)value * 0.0001);
}

bool bms_bms_brick_voltages_max_brick_voltage_bms_is_in_range(uint16_t value)
{
    return (value <= 65000u);
}

uint16_t bms_bms_brick_voltages_min_brick_voltage_index_bms_encode(double value)
{
    return (uint16_t)(value);
}

double bms_bms_brick_voltages_min_brick_voltage_index_bms_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_bms_brick_voltages_min_brick_voltage_index_bms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_bms_brick_voltages_max_brick_voltage_index_bms_encode(double value)
{
    return (uint16_t)(value);
}

double bms_bms_brick_voltages_max_brick_voltage_index_bms_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_bms_brick_voltages_max_brick_voltage_index_bms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int bms_bms_drive_limits_pack(
    uint8_t *dst_p,
    const struct bms_bms_drive_limits_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->max_voltage_limit_bms, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->max_voltage_limit_bms, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->min_voltage_limit_bms, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->min_voltage_limit_bms, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->regen_current_limit_bms, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->regen_current_limit_bms, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->discharge_current_limit_bms, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->discharge_current_limit_bms, 0u, 0xffu);

    return (8);
}

int bms_bms_drive_limits_unpack(
    struct bms_bms_drive_limits_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->max_voltage_limit_bms = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->max_voltage_limit_bms |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->min_voltage_limit_bms = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->min_voltage_limit_bms |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->regen_current_limit_bms = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->regen_current_limit_bms |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->discharge_current_limit_bms = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->discharge_current_limit_bms |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

uint16_t bms_bms_drive_limits_max_voltage_limit_bms_encode(double value)
{
    return (uint16_t)(value / 0.02);
}

double bms_bms_drive_limits_max_voltage_limit_bms_decode(uint16_t value)
{
    return ((double)value * 0.02);
}

bool bms_bms_drive_limits_max_voltage_limit_bms_is_in_range(uint16_t value)
{
    return (value <= 60000u);
}

uint16_t bms_bms_drive_limits_min_voltage_limit_bms_encode(double value)
{
    return (uint16_t)(value / 0.02);
}

double bms_bms_drive_limits_min_voltage_limit_bms_decode(uint16_t value)
{
    return ((double)value * 0.02);
}

bool bms_bms_drive_limits_min_voltage_limit_bms_is_in_range(uint16_t value)
{
    return (value <= 60000u);
}

uint16_t bms_bms_drive_limits_regen_current_limit_bms_encode(double value)
{
    return (uint16_t)(value / 0.05);
}

double bms_bms_drive_limits_regen_current_limit_bms_decode(uint16_t value)
{
    return ((double)value * 0.05);
}

bool bms_bms_drive_limits_regen_current_limit_bms_is_in_range(uint16_t value)
{
    return (value <= 64000u);
}

uint16_t bms_bms_drive_limits_discharge_current_limit_bms_encode(double value)
{
    return (uint16_t)(value / 0.05);
}

double bms_bms_drive_limits_discharge_current_limit_bms_decode(uint16_t value)
{
    return ((double)value * 0.05);
}

bool bms_bms_drive_limits_discharge_current_limit_bms_is_in_range(uint16_t value)
{
    return (value <= 64000u);
}

int bms_bms_state_pack(
    uint8_t *dst_p,
    const struct bms_bms_state_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->isolation_state_bms, 6u, 0xc0u);
    dst_p[0] |= pack_left_shift_u8(src_p->charge_state_bms, 4u, 0x30u);
    dst_p[0] |= pack_left_shift_u8(src_p->state_bms, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->number_of_connected_strings_bms, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->isolation_error_bms, 6u, 0xc0u);
    dst_p[2] |= pack_left_shift_u8(src_p->hvil_state_bms, 4u, 0x30u);
    dst_p[2] |= pack_left_shift_u8(src_p->state_tr_bms, 0u, 0x0fu);
    dst_p[3] |= pack_left_shift_u8(src_p->cntr_state_aux4_bms, 6u, 0xc0u);
    dst_p[3] |= pack_left_shift_u8(src_p->cntr_state_aux3_bms, 4u, 0x30u);
    dst_p[3] |= pack_left_shift_u8(src_p->cntr_state_aux2_bms, 2u, 0x0cu);
    dst_p[3] |= pack_left_shift_u8(src_p->cntr_state_aux1_bms, 0u, 0x03u);
    dst_p[4] |= pack_left_shift_u8(src_p->state_tr_index_bms, 3u, 0xf8u);

    return (5);
}

int bms_bms_state_unpack(
    struct bms_bms_state_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->isolation_state_bms = unpack_right_shift_u8(src_p[0], 6u, 0xc0u);
    dst_p->charge_state_bms = unpack_right_shift_u8(src_p[0], 4u, 0x30u);
    dst_p->state_bms = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->number_of_connected_strings_bms = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->isolation_error_bms = unpack_right_shift_u8(src_p[2], 6u, 0xc0u);
    dst_p->hvil_state_bms = unpack_right_shift_u8(src_p[2], 4u, 0x30u);
    dst_p->state_tr_bms = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->cntr_state_aux4_bms = unpack_right_shift_u8(src_p[3], 6u, 0xc0u);
    dst_p->cntr_state_aux3_bms = unpack_right_shift_u8(src_p[3], 4u, 0x30u);
    dst_p->cntr_state_aux2_bms = unpack_right_shift_u8(src_p[3], 2u, 0x0cu);
    dst_p->cntr_state_aux1_bms = unpack_right_shift_u8(src_p[3], 0u, 0x03u);
    dst_p->state_tr_index_bms = unpack_right_shift_u8(src_p[4], 3u, 0xf8u);

    return (0);
}

uint8_t bms_bms_state_isolation_state_bms_encode(double value)
{
    return (uint8_t)(value);
}

double bms_bms_state_isolation_state_bms_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_bms_state_isolation_state_bms_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t bms_bms_state_charge_state_bms_encode(double value)
{
    return (uint8_t)(value);
}

double bms_bms_state_charge_state_bms_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_bms_state_charge_state_bms_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t bms_bms_state_state_bms_encode(double value)
{
    return (uint8_t)(value);
}

double bms_bms_state_state_bms_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_bms_state_state_bms_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t bms_bms_state_number_of_connected_strings_bms_encode(double value)
{
    return (uint8_t)(value);
}

double bms_bms_state_number_of_connected_strings_bms_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_bms_state_number_of_connected_strings_bms_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t bms_bms_state_isolation_error_bms_encode(double value)
{
    return (uint8_t)(value);
}

double bms_bms_state_isolation_error_bms_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_bms_state_isolation_error_bms_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t bms_bms_state_hvil_state_bms_encode(double value)
{
    return (uint8_t)(value);
}

double bms_bms_state_hvil_state_bms_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_bms_state_hvil_state_bms_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t bms_bms_state_state_tr_bms_encode(double value)
{
    return (uint8_t)(value);
}

double bms_bms_state_state_tr_bms_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_bms_state_state_tr_bms_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t bms_bms_state_cntr_state_aux4_bms_encode(double value)
{
    return (uint8_t)(value);
}

double bms_bms_state_cntr_state_aux4_bms_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_bms_state_cntr_state_aux4_bms_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t bms_bms_state_cntr_state_aux3_bms_encode(double value)
{
    return (uint8_t)(value);
}

double bms_bms_state_cntr_state_aux3_bms_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_bms_state_cntr_state_aux3_bms_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t bms_bms_state_cntr_state_aux2_bms_encode(double value)
{
    return (uint8_t)(value);
}

double bms_bms_state_cntr_state_aux2_bms_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_bms_state_cntr_state_aux2_bms_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t bms_bms_state_cntr_state_aux1_bms_encode(double value)
{
    return (uint8_t)(value);
}

double bms_bms_state_cntr_state_aux1_bms_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_bms_state_cntr_state_aux1_bms_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t bms_bms_state_state_tr_index_bms_encode(double value)
{
    return (uint8_t)(value);
}

double bms_bms_state_state_tr_index_bms_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_bms_state_state_tr_index_bms_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

int bms_bms_current_voltage_pack(
    uint8_t *dst_p,
    const struct bms_bms_current_voltage_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->link_voltage_bms, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->link_voltage_bms, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->current_bms, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->current_bms, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->discharge_current_residual_bms, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->discharge_current_residual_bms, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->regen_current_residual_bms, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->regen_current_residual_bms, 0u, 0xffu);

    return (8);
}

int bms_bms_current_voltage_unpack(
    struct bms_bms_current_voltage_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->link_voltage_bms = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->link_voltage_bms |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->current_bms = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->current_bms |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->discharge_current_residual_bms = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->discharge_current_residual_bms |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->regen_current_residual_bms = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->regen_current_residual_bms |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

uint16_t bms_bms_current_voltage_link_voltage_bms_encode(double value)
{
    return (uint16_t)(value / 0.02);
}

double bms_bms_current_voltage_link_voltage_bms_decode(uint16_t value)
{
    return ((double)value * 0.02);
}

bool bms_bms_current_voltage_link_voltage_bms_is_in_range(uint16_t value)
{
    return (value <= 60000u);
}

uint16_t bms_bms_current_voltage_current_bms_encode(double value)
{
    return (uint16_t)((value - -3200.0) / 0.1);
}

double bms_bms_current_voltage_current_bms_decode(uint16_t value)
{
    return (((double)value * 0.1) + -3200.0);
}

bool bms_bms_current_voltage_current_bms_is_in_range(uint16_t value)
{
    return (value <= 64000u);
}

uint16_t bms_bms_current_voltage_discharge_current_residual_bms_encode(double value)
{
    return (uint16_t)((value - -3200.0) / 0.1);
}

double bms_bms_current_voltage_discharge_current_residual_bms_decode(uint16_t value)
{
    return (((double)value * 0.1) + -3200.0);
}

bool bms_bms_current_voltage_discharge_current_residual_bms_is_in_range(uint16_t value)
{
    return (value <= 64000u);
}

uint16_t bms_bms_current_voltage_regen_current_residual_bms_encode(double value)
{
    return (uint16_t)((value - -3200.0) / 0.1);
}

double bms_bms_current_voltage_regen_current_residual_bms_decode(uint16_t value)
{
    return (((double)value * 0.1) + -3200.0);
}

bool bms_bms_current_voltage_regen_current_residual_bms_is_in_range(uint16_t value)
{
    return (value <= 64000u);
}

int bms_pt_request_pack(
    uint8_t *dst_p,
    const struct bms_pt_request_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->isolation_request_pt, 4u, 0xf0u);
    dst_p[0] |= pack_left_shift_u8(src_p->state_request_pt, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->range_request_pt, 4u, 0xf0u);
    dst_p[1] |= pack_left_shift_u8(src_p->sleep_request_pt, 0u, 0x0fu);
    dst_p[2] |= pack_right_shift_u16(src_p->charge_power_available_pt, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->charge_power_available_pt, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->alive_pt, 4u, 0xf0u);
    dst_p[5] |= pack_left_shift_u8(src_p->cntr_request_aux4_pt, 3u, 0x08u);
    dst_p[5] |= pack_left_shift_u8(src_p->cntr_request_aux3_pt, 2u, 0x04u);
    dst_p[5] |= pack_left_shift_u8(src_p->cntr_request_aux2_pt, 1u, 0x02u);
    dst_p[5] |= pack_left_shift_u8(src_p->cntr_request_aux1_pt, 0u, 0x01u);
    dst_p[6] |= pack_left_shift_u8(src_p->crc_pt, 0u, 0xffu);

    return (7);
}

int bms_pt_request_unpack(
    struct bms_pt_request_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->isolation_request_pt = unpack_right_shift_u8(src_p[0], 4u, 0xf0u);
    dst_p->state_request_pt = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->range_request_pt = unpack_right_shift_u8(src_p[1], 4u, 0xf0u);
    dst_p->sleep_request_pt = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);
    dst_p->charge_power_available_pt = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->charge_power_available_pt |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->alive_pt = unpack_right_shift_u8(src_p[5], 4u, 0xf0u);
    dst_p->cntr_request_aux4_pt = unpack_right_shift_u8(src_p[5], 3u, 0x08u);
    dst_p->cntr_request_aux3_pt = unpack_right_shift_u8(src_p[5], 2u, 0x04u);
    dst_p->cntr_request_aux2_pt = unpack_right_shift_u8(src_p[5], 1u, 0x02u);
    dst_p->cntr_request_aux1_pt = unpack_right_shift_u8(src_p[5], 0u, 0x01u);
    dst_p->crc_pt = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

uint8_t bms_pt_request_isolation_request_pt_encode(double value)
{
    return (uint8_t)(value);
}

double bms_pt_request_isolation_request_pt_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_pt_request_isolation_request_pt_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t bms_pt_request_state_request_pt_encode(double value)
{
    return (uint8_t)(value);
}

double bms_pt_request_state_request_pt_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_pt_request_state_request_pt_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t bms_pt_request_range_request_pt_encode(double value)
{
    return (uint8_t)(value);
}

double bms_pt_request_range_request_pt_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_pt_request_range_request_pt_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t bms_pt_request_sleep_request_pt_encode(double value)
{
    return (uint8_t)(value);
}

double bms_pt_request_sleep_request_pt_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_pt_request_sleep_request_pt_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t bms_pt_request_charge_power_available_pt_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double bms_pt_request_charge_power_available_pt_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool bms_pt_request_charge_power_available_pt_is_in_range(uint16_t value)
{
    return (value <= 65000u);
}

uint8_t bms_pt_request_alive_pt_encode(double value)
{
    return (uint8_t)(value);
}

double bms_pt_request_alive_pt_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_pt_request_alive_pt_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t bms_pt_request_cntr_request_aux4_pt_encode(double value)
{
    return (uint8_t)(value);
}

double bms_pt_request_cntr_request_aux4_pt_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_pt_request_cntr_request_aux4_pt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_pt_request_cntr_request_aux3_pt_encode(double value)
{
    return (uint8_t)(value);
}

double bms_pt_request_cntr_request_aux3_pt_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_pt_request_cntr_request_aux3_pt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_pt_request_cntr_request_aux2_pt_encode(double value)
{
    return (uint8_t)(value);
}

double bms_pt_request_cntr_request_aux2_pt_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_pt_request_cntr_request_aux2_pt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_pt_request_cntr_request_aux1_pt_encode(double value)
{
    return (uint8_t)(value);
}

double bms_pt_request_cntr_request_aux1_pt_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_pt_request_cntr_request_aux1_pt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_pt_request_crc_pt_encode(double value)
{
    return (uint8_t)(value);
}

double bms_pt_request_crc_pt_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_pt_request_crc_pt_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
