/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.2.0 Fri Apr 26 11:29:19 2024.
 */

#include <string.h>

#include "dom.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int dom_engine_parameters_rapid_update_pack(
    uint8_t *dst_p,
    const struct dom_engine_parameters_rapid_update_t *src_p,
    size_t size)
{
    uint8_t engine_tilt_trim;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->engine_instance, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->engine_speed, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->engine_speed, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->engine_boost_pressure, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->engine_boost_pressure, 8u, 0xffu);
    engine_tilt_trim = (uint8_t)src_p->engine_tilt_trim;
    dst_p[5] |= pack_left_shift_u8(engine_tilt_trim, 0u, 0xffu);

    return (8);
}

int dom_engine_parameters_rapid_update_unpack(
    struct dom_engine_parameters_rapid_update_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t engine_tilt_trim;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->engine_instance = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->engine_speed = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->engine_speed |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->engine_boost_pressure = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->engine_boost_pressure |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    engine_tilt_trim = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->engine_tilt_trim = (int8_t)engine_tilt_trim;

    return (0);
}

int dom_engine_parameters_rapid_update_init(struct dom_engine_parameters_rapid_update_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct dom_engine_parameters_rapid_update_t));

    return 0;
}

uint8_t dom_engine_parameters_rapid_update_engine_instance_encode(double value)
{
    return (uint8_t)(value);
}

double dom_engine_parameters_rapid_update_engine_instance_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_engine_parameters_rapid_update_engine_instance_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t dom_engine_parameters_rapid_update_engine_speed_encode(double value)
{
    return (uint16_t)(value / 0.25);
}

double dom_engine_parameters_rapid_update_engine_speed_decode(uint16_t value)
{
    return ((double)value * 0.25);
}

bool dom_engine_parameters_rapid_update_engine_speed_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t dom_engine_parameters_rapid_update_engine_boost_pressure_encode(double value)
{
    return (uint16_t)(value / 100.0);
}

double dom_engine_parameters_rapid_update_engine_boost_pressure_decode(uint16_t value)
{
    return ((double)value * 100.0);
}

bool dom_engine_parameters_rapid_update_engine_boost_pressure_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int8_t dom_engine_parameters_rapid_update_engine_tilt_trim_encode(double value)
{
    return (int8_t)(value);
}

double dom_engine_parameters_rapid_update_engine_tilt_trim_decode(int8_t value)
{
    return ((double)value);
}

bool dom_engine_parameters_rapid_update_engine_tilt_trim_is_in_range(int8_t value)
{
    return ((value >= -124) && (value <= 124));
}

int dom_actuator_cmd_stbd_joy_pack(
    uint8_t *dst_p,
    const struct dom_actuator_cmd_stbd_joy_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->manufacturer_id, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->manufacturer_id, 8u, 0x07u);
    dst_p[1] |= pack_left_shift_u8(src_p->reserved_1, 3u, 0x18u);
    dst_p[1] |= pack_left_shift_u8(src_p->industry_group, 5u, 0xe0u);
    dst_p[2] |= pack_left_shift_u8(src_p->source_instance, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->reserved_2, 4u, 0x30u);
    dst_p[2] |= pack_left_shift_u8(src_p->reserved_3, 6u, 0xc0u);
    dst_p[3] |= pack_left_shift_u8(src_p->gear_command, 0u, 0x0fu);
    dst_p[3] |= pack_left_shift_u8(src_p->reserved_4, 4u, 0xf0u);
    dst_p[4] |= pack_left_shift_u16(src_p->throttle_command, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->throttle_command, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->reserved_5, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->reserved_6, 0u, 0xffu);

    return (8);
}

int dom_actuator_cmd_stbd_joy_unpack(
    struct dom_actuator_cmd_stbd_joy_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->manufacturer_id = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->manufacturer_id |= unpack_left_shift_u16(src_p[1], 8u, 0x07u);
    dst_p->reserved_1 = unpack_right_shift_u8(src_p[1], 3u, 0x18u);
    dst_p->industry_group = unpack_right_shift_u8(src_p[1], 5u, 0xe0u);
    dst_p->source_instance = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->reserved_2 = unpack_right_shift_u8(src_p[2], 4u, 0x30u);
    dst_p->reserved_3 = unpack_right_shift_u8(src_p[2], 6u, 0xc0u);
    dst_p->gear_command = unpack_right_shift_u8(src_p[3], 0u, 0x0fu);
    dst_p->reserved_4 = unpack_right_shift_u8(src_p[3], 4u, 0xf0u);
    dst_p->throttle_command = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->throttle_command |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->reserved_5 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->reserved_6 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int dom_actuator_cmd_stbd_joy_init(struct dom_actuator_cmd_stbd_joy_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct dom_actuator_cmd_stbd_joy_t));

    return 0;
}

uint16_t dom_actuator_cmd_stbd_joy_manufacturer_id_encode(double value)
{
    return (uint16_t)(value);
}

double dom_actuator_cmd_stbd_joy_manufacturer_id_decode(uint16_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_joy_manufacturer_id_is_in_range(uint16_t value)
{
    return (value <= 2047u);
}

uint8_t dom_actuator_cmd_stbd_joy_reserved_1_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_joy_reserved_1_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_joy_reserved_1_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_cmd_stbd_joy_industry_group_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_joy_industry_group_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_joy_industry_group_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t dom_actuator_cmd_stbd_joy_source_instance_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_joy_source_instance_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_joy_source_instance_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dom_actuator_cmd_stbd_joy_reserved_2_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_joy_reserved_2_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_joy_reserved_2_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_cmd_stbd_joy_reserved_3_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_joy_reserved_3_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_joy_reserved_3_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_cmd_stbd_joy_gear_command_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_joy_gear_command_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_joy_gear_command_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dom_actuator_cmd_stbd_joy_reserved_4_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_joy_reserved_4_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_joy_reserved_4_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t dom_actuator_cmd_stbd_joy_throttle_command_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double dom_actuator_cmd_stbd_joy_throttle_command_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool dom_actuator_cmd_stbd_joy_throttle_command_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

uint8_t dom_actuator_cmd_stbd_joy_reserved_5_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_joy_reserved_5_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_joy_reserved_5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t dom_actuator_cmd_stbd_joy_reserved_6_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_joy_reserved_6_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_joy_reserved_6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int dom_actuator_cmd_port_joy_pack(
    uint8_t *dst_p,
    const struct dom_actuator_cmd_port_joy_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->manufacturer_id, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->manufacturer_id, 8u, 0x07u);
    dst_p[1] |= pack_left_shift_u8(src_p->reserved_1, 3u, 0x18u);
    dst_p[1] |= pack_left_shift_u8(src_p->industry_group, 5u, 0xe0u);
    dst_p[2] |= pack_left_shift_u8(src_p->source_instance, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->reserved_2, 4u, 0x30u);
    dst_p[2] |= pack_left_shift_u8(src_p->reserved_3, 6u, 0xc0u);
    dst_p[3] |= pack_left_shift_u8(src_p->gear_command, 0u, 0x0fu);
    dst_p[3] |= pack_left_shift_u8(src_p->reserved_4, 4u, 0xf0u);
    dst_p[4] |= pack_left_shift_u16(src_p->throttle_command, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->throttle_command, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->reserved_5, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->reserved_6, 0u, 0xffu);

    return (8);
}

int dom_actuator_cmd_port_joy_unpack(
    struct dom_actuator_cmd_port_joy_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->manufacturer_id = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->manufacturer_id |= unpack_left_shift_u16(src_p[1], 8u, 0x07u);
    dst_p->reserved_1 = unpack_right_shift_u8(src_p[1], 3u, 0x18u);
    dst_p->industry_group = unpack_right_shift_u8(src_p[1], 5u, 0xe0u);
    dst_p->source_instance = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->reserved_2 = unpack_right_shift_u8(src_p[2], 4u, 0x30u);
    dst_p->reserved_3 = unpack_right_shift_u8(src_p[2], 6u, 0xc0u);
    dst_p->gear_command = unpack_right_shift_u8(src_p[3], 0u, 0x0fu);
    dst_p->reserved_4 = unpack_right_shift_u8(src_p[3], 4u, 0xf0u);
    dst_p->throttle_command = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->throttle_command |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->reserved_5 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->reserved_6 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int dom_actuator_cmd_port_joy_init(struct dom_actuator_cmd_port_joy_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct dom_actuator_cmd_port_joy_t));

    return 0;
}

uint16_t dom_actuator_cmd_port_joy_manufacturer_id_encode(double value)
{
    return (uint16_t)(value);
}

double dom_actuator_cmd_port_joy_manufacturer_id_decode(uint16_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_joy_manufacturer_id_is_in_range(uint16_t value)
{
    return (value <= 2047u);
}

uint8_t dom_actuator_cmd_port_joy_reserved_1_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_joy_reserved_1_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_joy_reserved_1_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_cmd_port_joy_industry_group_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_joy_industry_group_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_joy_industry_group_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t dom_actuator_cmd_port_joy_source_instance_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_joy_source_instance_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_joy_source_instance_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dom_actuator_cmd_port_joy_reserved_2_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_joy_reserved_2_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_joy_reserved_2_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_cmd_port_joy_reserved_3_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_joy_reserved_3_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_joy_reserved_3_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_cmd_port_joy_gear_command_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_joy_gear_command_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_joy_gear_command_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dom_actuator_cmd_port_joy_reserved_4_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_joy_reserved_4_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_joy_reserved_4_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t dom_actuator_cmd_port_joy_throttle_command_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double dom_actuator_cmd_port_joy_throttle_command_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool dom_actuator_cmd_port_joy_throttle_command_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

uint8_t dom_actuator_cmd_port_joy_reserved_5_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_joy_reserved_5_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_joy_reserved_5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t dom_actuator_cmd_port_joy_reserved_6_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_joy_reserved_6_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_joy_reserved_6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int dom_address_claim_pack(
    uint8_t *dst_p,
    const struct dom_address_claim_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->identity_number, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->identity_number, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->identity_number, 16u, 0x1fu);
    dst_p[2] |= pack_left_shift_u16(src_p->manufacturer_code, 5u, 0xe0u);
    dst_p[3] |= pack_right_shift_u16(src_p->manufacturer_code, 3u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->ecu_instance, 0u, 0x07u);
    dst_p[4] |= pack_left_shift_u8(src_p->function_instance, 3u, 0xf8u);
    dst_p[5] |= pack_left_shift_u8(src_p->function, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->reserved_bit, 0u, 0x01u);
    dst_p[6] |= pack_left_shift_u8(src_p->vehicle_system, 1u, 0xfeu);
    dst_p[7] |= pack_left_shift_u8(src_p->vehicle_system_instance, 0u, 0x0fu);
    dst_p[7] |= pack_left_shift_u8(src_p->industry_group, 4u, 0x70u);
    dst_p[7] |= pack_left_shift_u8(src_p->arbitrary_address_bit, 7u, 0x80u);

    return (8);
}

int dom_address_claim_unpack(
    struct dom_address_claim_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->identity_number = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->identity_number |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->identity_number |= unpack_left_shift_u32(src_p[2], 16u, 0x1fu);
    dst_p->manufacturer_code = unpack_right_shift_u16(src_p[2], 5u, 0xe0u);
    dst_p->manufacturer_code |= unpack_left_shift_u16(src_p[3], 3u, 0xffu);
    dst_p->ecu_instance = unpack_right_shift_u8(src_p[4], 0u, 0x07u);
    dst_p->function_instance = unpack_right_shift_u8(src_p[4], 3u, 0xf8u);
    dst_p->function = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->reserved_bit = unpack_right_shift_u8(src_p[6], 0u, 0x01u);
    dst_p->vehicle_system = unpack_right_shift_u8(src_p[6], 1u, 0xfeu);
    dst_p->vehicle_system_instance = unpack_right_shift_u8(src_p[7], 0u, 0x0fu);
    dst_p->industry_group = unpack_right_shift_u8(src_p[7], 4u, 0x70u);
    dst_p->arbitrary_address_bit = unpack_right_shift_u8(src_p[7], 7u, 0x80u);

    return (0);
}

int dom_address_claim_init(struct dom_address_claim_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct dom_address_claim_t));

    return 0;
}

uint32_t dom_address_claim_identity_number_encode(double value)
{
    return (uint32_t)(value);
}

double dom_address_claim_identity_number_decode(uint32_t value)
{
    return ((double)value);
}

bool dom_address_claim_identity_number_is_in_range(uint32_t value)
{
    return (value <= 2097151u);
}

uint16_t dom_address_claim_manufacturer_code_encode(double value)
{
    return (uint16_t)(value);
}

double dom_address_claim_manufacturer_code_decode(uint16_t value)
{
    return ((double)value);
}

bool dom_address_claim_manufacturer_code_is_in_range(uint16_t value)
{
    return (value <= 2047u);
}

uint8_t dom_address_claim_ecu_instance_encode(double value)
{
    return (uint8_t)(value);
}

double dom_address_claim_ecu_instance_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_address_claim_ecu_instance_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t dom_address_claim_function_instance_encode(double value)
{
    return (uint8_t)(value);
}

double dom_address_claim_function_instance_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_address_claim_function_instance_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

uint8_t dom_address_claim_function_encode(double value)
{
    return (uint8_t)(value);
}

double dom_address_claim_function_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_address_claim_function_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t dom_address_claim_reserved_bit_encode(double value)
{
    return (uint8_t)(value);
}

double dom_address_claim_reserved_bit_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_address_claim_reserved_bit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_address_claim_vehicle_system_encode(double value)
{
    return (uint8_t)(value);
}

double dom_address_claim_vehicle_system_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_address_claim_vehicle_system_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

uint8_t dom_address_claim_vehicle_system_instance_encode(double value)
{
    return (uint8_t)(value);
}

double dom_address_claim_vehicle_system_instance_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_address_claim_vehicle_system_instance_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dom_address_claim_industry_group_encode(double value)
{
    return (uint8_t)(value);
}

double dom_address_claim_industry_group_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_address_claim_industry_group_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t dom_address_claim_arbitrary_address_bit_encode(double value)
{
    return (uint8_t)(value);
}

double dom_address_claim_arbitrary_address_bit_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_address_claim_arbitrary_address_bit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int dom_actuator_feedback_stbd_pack(
    uint8_t *dst_p,
    const struct dom_actuator_feedback_stbd_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->manufacturer_id, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->manufacturer_id, 8u, 0x07u);
    dst_p[1] |= pack_left_shift_u8(src_p->reserved_1, 3u, 0x18u);
    dst_p[1] |= pack_left_shift_u8(src_p->industry_group, 5u, 0xe0u);
    dst_p[2] |= pack_left_shift_u8(src_p->engine_instance, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->actuator_type, 4u, 0x30u);
    dst_p[2] |= pack_left_shift_u8(src_p->reserved, 6u, 0xc0u);
    dst_p[3] |= pack_left_shift_u8(src_p->actual_gear_value, 0u, 0x0fu);
    dst_p[3] |= pack_left_shift_u8(src_p->control_state, 4u, 0xf0u);
    dst_p[4] |= pack_left_shift_u16(src_p->actual_throttle_value, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->actual_throttle_value, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->reserved_2, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->danger_fault, 0u, 0x01u);
    dst_p[7] |= pack_left_shift_u8(src_p->warning_fault, 1u, 0x02u);
    dst_p[7] |= pack_left_shift_u8(src_p->shift_forward_fault, 2u, 0x04u);
    dst_p[7] |= pack_left_shift_u8(src_p->shift_neutral_fault, 3u, 0x08u);
    dst_p[7] |= pack_left_shift_u8(src_p->shift_reverse_fault, 4u, 0x10u);
    dst_p[7] |= pack_left_shift_u8(src_p->throttle_up_fault, 5u, 0x20u);
    dst_p[7] |= pack_left_shift_u8(src_p->throttle_down_fault, 6u, 0x40u);
    dst_p[7] |= pack_left_shift_u8(src_p->reserved_3, 7u, 0x80u);

    return (8);
}

int dom_actuator_feedback_stbd_unpack(
    struct dom_actuator_feedback_stbd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->manufacturer_id = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->manufacturer_id |= unpack_left_shift_u16(src_p[1], 8u, 0x07u);
    dst_p->reserved_1 = unpack_right_shift_u8(src_p[1], 3u, 0x18u);
    dst_p->industry_group = unpack_right_shift_u8(src_p[1], 5u, 0xe0u);
    dst_p->engine_instance = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->actuator_type = unpack_right_shift_u8(src_p[2], 4u, 0x30u);
    dst_p->reserved = unpack_right_shift_u8(src_p[2], 6u, 0xc0u);
    dst_p->actual_gear_value = unpack_right_shift_u8(src_p[3], 0u, 0x0fu);
    dst_p->control_state = unpack_right_shift_u8(src_p[3], 4u, 0xf0u);
    dst_p->actual_throttle_value = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->actual_throttle_value |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->reserved_2 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->danger_fault = unpack_right_shift_u8(src_p[7], 0u, 0x01u);
    dst_p->warning_fault = unpack_right_shift_u8(src_p[7], 1u, 0x02u);
    dst_p->shift_forward_fault = unpack_right_shift_u8(src_p[7], 2u, 0x04u);
    dst_p->shift_neutral_fault = unpack_right_shift_u8(src_p[7], 3u, 0x08u);
    dst_p->shift_reverse_fault = unpack_right_shift_u8(src_p[7], 4u, 0x10u);
    dst_p->throttle_up_fault = unpack_right_shift_u8(src_p[7], 5u, 0x20u);
    dst_p->throttle_down_fault = unpack_right_shift_u8(src_p[7], 6u, 0x40u);
    dst_p->reserved_3 = unpack_right_shift_u8(src_p[7], 7u, 0x80u);

    return (0);
}

int dom_actuator_feedback_stbd_init(struct dom_actuator_feedback_stbd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct dom_actuator_feedback_stbd_t));

    return 0;
}

uint16_t dom_actuator_feedback_stbd_manufacturer_id_encode(double value)
{
    return (uint16_t)(value);
}

double dom_actuator_feedback_stbd_manufacturer_id_decode(uint16_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_stbd_manufacturer_id_is_in_range(uint16_t value)
{
    return (value <= 2047u);
}

uint8_t dom_actuator_feedback_stbd_reserved_1_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_stbd_reserved_1_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_stbd_reserved_1_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_feedback_stbd_industry_group_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_stbd_industry_group_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_stbd_industry_group_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t dom_actuator_feedback_stbd_engine_instance_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_stbd_engine_instance_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_stbd_engine_instance_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dom_actuator_feedback_stbd_actuator_type_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_stbd_actuator_type_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_stbd_actuator_type_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_feedback_stbd_reserved_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_stbd_reserved_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_stbd_reserved_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_feedback_stbd_actual_gear_value_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_stbd_actual_gear_value_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_stbd_actual_gear_value_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dom_actuator_feedback_stbd_control_state_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_stbd_control_state_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_stbd_control_state_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t dom_actuator_feedback_stbd_actual_throttle_value_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double dom_actuator_feedback_stbd_actual_throttle_value_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool dom_actuator_feedback_stbd_actual_throttle_value_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

uint8_t dom_actuator_feedback_stbd_reserved_2_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_stbd_reserved_2_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_stbd_reserved_2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t dom_actuator_feedback_stbd_danger_fault_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_stbd_danger_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_stbd_danger_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_actuator_feedback_stbd_warning_fault_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_stbd_warning_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_stbd_warning_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_actuator_feedback_stbd_shift_forward_fault_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_stbd_shift_forward_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_stbd_shift_forward_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_actuator_feedback_stbd_shift_neutral_fault_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_stbd_shift_neutral_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_stbd_shift_neutral_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_actuator_feedback_stbd_shift_reverse_fault_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_stbd_shift_reverse_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_stbd_shift_reverse_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_actuator_feedback_stbd_throttle_up_fault_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_stbd_throttle_up_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_stbd_throttle_up_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_actuator_feedback_stbd_throttle_down_fault_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_stbd_throttle_down_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_stbd_throttle_down_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_actuator_feedback_stbd_reserved_3_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_stbd_reserved_3_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_stbd_reserved_3_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int dom_control_head_feedback_pack(
    uint8_t *dst_p,
    const struct dom_control_head_feedback_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->manufacturer_id, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->manufacturer_id, 8u, 0x07u);
    dst_p[1] |= pack_left_shift_u8(src_p->reserved_1, 3u, 0x18u);
    dst_p[1] |= pack_left_shift_u8(src_p->industry_group, 5u, 0xe0u);
    dst_p[2] |= pack_left_shift_u8(src_p->source_instance, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->reserved_2, 4u, 0xf0u);
    dst_p[3] |= pack_left_shift_u8(src_p->port_lever_gaer_position, 0u, 0x0fu);
    dst_p[3] |= pack_left_shift_u8(src_p->stbd_lever_gaer_position, 4u, 0xf0u);
    dst_p[4] |= pack_left_shift_u8(src_p->port_lever_throttle_position, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->stbd_lever_throttle_position, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->reserved_3, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->danger_fault, 0u, 0x01u);
    dst_p[7] |= pack_left_shift_u8(src_p->warning_fault, 1u, 0x02u);
    dst_p[7] |= pack_left_shift_u8(src_p->ch_controlling, 2u, 0x04u);
    dst_p[7] |= pack_left_shift_u8(src_p->port_ntw_active, 3u, 0x08u);
    dst_p[7] |= pack_left_shift_u8(src_p->stbd_ntw_active, 4u, 0x10u);
    dst_p[7] |= pack_left_shift_u8(src_p->sync_mode_active, 5u, 0x20u);
    dst_p[7] |= pack_left_shift_u8(src_p->reserved_4, 6u, 0xc0u);

    return (8);
}

int dom_control_head_feedback_unpack(
    struct dom_control_head_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->manufacturer_id = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->manufacturer_id |= unpack_left_shift_u16(src_p[1], 8u, 0x07u);
    dst_p->reserved_1 = unpack_right_shift_u8(src_p[1], 3u, 0x18u);
    dst_p->industry_group = unpack_right_shift_u8(src_p[1], 5u, 0xe0u);
    dst_p->source_instance = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->reserved_2 = unpack_right_shift_u8(src_p[2], 4u, 0xf0u);
    dst_p->port_lever_gaer_position = unpack_right_shift_u8(src_p[3], 0u, 0x0fu);
    dst_p->stbd_lever_gaer_position = unpack_right_shift_u8(src_p[3], 4u, 0xf0u);
    dst_p->port_lever_throttle_position = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->stbd_lever_throttle_position = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->reserved_3 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->danger_fault = unpack_right_shift_u8(src_p[7], 0u, 0x01u);
    dst_p->warning_fault = unpack_right_shift_u8(src_p[7], 1u, 0x02u);
    dst_p->ch_controlling = unpack_right_shift_u8(src_p[7], 2u, 0x04u);
    dst_p->port_ntw_active = unpack_right_shift_u8(src_p[7], 3u, 0x08u);
    dst_p->stbd_ntw_active = unpack_right_shift_u8(src_p[7], 4u, 0x10u);
    dst_p->sync_mode_active = unpack_right_shift_u8(src_p[7], 5u, 0x20u);
    dst_p->reserved_4 = unpack_right_shift_u8(src_p[7], 6u, 0xc0u);

    return (0);
}

int dom_control_head_feedback_init(struct dom_control_head_feedback_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct dom_control_head_feedback_t));

    return 0;
}

uint16_t dom_control_head_feedback_manufacturer_id_encode(double value)
{
    return (uint16_t)(value);
}

double dom_control_head_feedback_manufacturer_id_decode(uint16_t value)
{
    return ((double)value);
}

bool dom_control_head_feedback_manufacturer_id_is_in_range(uint16_t value)
{
    return (value <= 2047u);
}

uint8_t dom_control_head_feedback_reserved_1_encode(double value)
{
    return (uint8_t)(value);
}

double dom_control_head_feedback_reserved_1_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_control_head_feedback_reserved_1_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_control_head_feedback_industry_group_encode(double value)
{
    return (uint8_t)(value);
}

double dom_control_head_feedback_industry_group_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_control_head_feedback_industry_group_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t dom_control_head_feedback_source_instance_encode(double value)
{
    return (uint8_t)(value);
}

double dom_control_head_feedback_source_instance_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_control_head_feedback_source_instance_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dom_control_head_feedback_reserved_2_encode(double value)
{
    return (uint8_t)(value);
}

double dom_control_head_feedback_reserved_2_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_control_head_feedback_reserved_2_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dom_control_head_feedback_port_lever_gaer_position_encode(double value)
{
    return (uint8_t)(value);
}

double dom_control_head_feedback_port_lever_gaer_position_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_control_head_feedback_port_lever_gaer_position_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dom_control_head_feedback_stbd_lever_gaer_position_encode(double value)
{
    return (uint8_t)(value);
}

double dom_control_head_feedback_stbd_lever_gaer_position_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_control_head_feedback_stbd_lever_gaer_position_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dom_control_head_feedback_port_lever_throttle_position_encode(double value)
{
    return (uint8_t)(value);
}

double dom_control_head_feedback_port_lever_throttle_position_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_control_head_feedback_port_lever_throttle_position_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t dom_control_head_feedback_stbd_lever_throttle_position_encode(double value)
{
    return (uint8_t)(value);
}

double dom_control_head_feedback_stbd_lever_throttle_position_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_control_head_feedback_stbd_lever_throttle_position_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t dom_control_head_feedback_reserved_3_encode(double value)
{
    return (uint8_t)(value);
}

double dom_control_head_feedback_reserved_3_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_control_head_feedback_reserved_3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t dom_control_head_feedback_danger_fault_encode(double value)
{
    return (uint8_t)(value);
}

double dom_control_head_feedback_danger_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_control_head_feedback_danger_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_control_head_feedback_warning_fault_encode(double value)
{
    return (uint8_t)(value);
}

double dom_control_head_feedback_warning_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_control_head_feedback_warning_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_control_head_feedback_ch_controlling_encode(double value)
{
    return (uint8_t)(value);
}

double dom_control_head_feedback_ch_controlling_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_control_head_feedback_ch_controlling_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_control_head_feedback_port_ntw_active_encode(double value)
{
    return (uint8_t)(value);
}

double dom_control_head_feedback_port_ntw_active_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_control_head_feedback_port_ntw_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_control_head_feedback_stbd_ntw_active_encode(double value)
{
    return (uint8_t)(value);
}

double dom_control_head_feedback_stbd_ntw_active_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_control_head_feedback_stbd_ntw_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_control_head_feedback_sync_mode_active_encode(double value)
{
    return (uint8_t)(value);
}

double dom_control_head_feedback_sync_mode_active_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_control_head_feedback_sync_mode_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_control_head_feedback_reserved_4_encode(double value)
{
    return (uint8_t)(value);
}

double dom_control_head_feedback_reserved_4_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_control_head_feedback_reserved_4_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int dom_actuator_feedback_port_pack(
    uint8_t *dst_p,
    const struct dom_actuator_feedback_port_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->manufacturer_id, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->manufacturer_id, 8u, 0x07u);
    dst_p[1] |= pack_left_shift_u8(src_p->reserved_1, 3u, 0x18u);
    dst_p[1] |= pack_left_shift_u8(src_p->industry_group, 5u, 0xe0u);
    dst_p[2] |= pack_left_shift_u8(src_p->engine_instance, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->actuator_type, 4u, 0x30u);
    dst_p[2] |= pack_left_shift_u8(src_p->reserved, 6u, 0xc0u);
    dst_p[3] |= pack_left_shift_u8(src_p->actual_gear_value, 0u, 0x0fu);
    dst_p[3] |= pack_left_shift_u8(src_p->control_state, 4u, 0xf0u);
    dst_p[4] |= pack_left_shift_u16(src_p->actual_throttle_value, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->actual_throttle_value, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->reserved_2, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->danger_fault, 0u, 0x01u);
    dst_p[7] |= pack_left_shift_u8(src_p->warning_fault, 1u, 0x02u);
    dst_p[7] |= pack_left_shift_u8(src_p->shift_forward_fault, 2u, 0x04u);
    dst_p[7] |= pack_left_shift_u8(src_p->shift_neutral_fault, 3u, 0x08u);
    dst_p[7] |= pack_left_shift_u8(src_p->shift_reverse_fault, 4u, 0x10u);
    dst_p[7] |= pack_left_shift_u8(src_p->throttle_up_fault, 5u, 0x20u);
    dst_p[7] |= pack_left_shift_u8(src_p->throttle_down_fault, 6u, 0x40u);
    dst_p[7] |= pack_left_shift_u8(src_p->reserved_3, 7u, 0x80u);

    return (8);
}

int dom_actuator_feedback_port_unpack(
    struct dom_actuator_feedback_port_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->manufacturer_id = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->manufacturer_id |= unpack_left_shift_u16(src_p[1], 8u, 0x07u);
    dst_p->reserved_1 = unpack_right_shift_u8(src_p[1], 3u, 0x18u);
    dst_p->industry_group = unpack_right_shift_u8(src_p[1], 5u, 0xe0u);
    dst_p->engine_instance = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->actuator_type = unpack_right_shift_u8(src_p[2], 4u, 0x30u);
    dst_p->reserved = unpack_right_shift_u8(src_p[2], 6u, 0xc0u);
    dst_p->actual_gear_value = unpack_right_shift_u8(src_p[3], 0u, 0x0fu);
    dst_p->control_state = unpack_right_shift_u8(src_p[3], 4u, 0xf0u);
    dst_p->actual_throttle_value = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->actual_throttle_value |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->reserved_2 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->danger_fault = unpack_right_shift_u8(src_p[7], 0u, 0x01u);
    dst_p->warning_fault = unpack_right_shift_u8(src_p[7], 1u, 0x02u);
    dst_p->shift_forward_fault = unpack_right_shift_u8(src_p[7], 2u, 0x04u);
    dst_p->shift_neutral_fault = unpack_right_shift_u8(src_p[7], 3u, 0x08u);
    dst_p->shift_reverse_fault = unpack_right_shift_u8(src_p[7], 4u, 0x10u);
    dst_p->throttle_up_fault = unpack_right_shift_u8(src_p[7], 5u, 0x20u);
    dst_p->throttle_down_fault = unpack_right_shift_u8(src_p[7], 6u, 0x40u);
    dst_p->reserved_3 = unpack_right_shift_u8(src_p[7], 7u, 0x80u);

    return (0);
}

int dom_actuator_feedback_port_init(struct dom_actuator_feedback_port_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct dom_actuator_feedback_port_t));

    return 0;
}

uint16_t dom_actuator_feedback_port_manufacturer_id_encode(double value)
{
    return (uint16_t)(value);
}

double dom_actuator_feedback_port_manufacturer_id_decode(uint16_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_port_manufacturer_id_is_in_range(uint16_t value)
{
    return (value <= 2047u);
}

uint8_t dom_actuator_feedback_port_reserved_1_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_port_reserved_1_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_port_reserved_1_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_feedback_port_industry_group_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_port_industry_group_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_port_industry_group_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t dom_actuator_feedback_port_engine_instance_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_port_engine_instance_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_port_engine_instance_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dom_actuator_feedback_port_actuator_type_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_port_actuator_type_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_port_actuator_type_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_feedback_port_reserved_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_port_reserved_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_port_reserved_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_feedback_port_actual_gear_value_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_port_actual_gear_value_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_port_actual_gear_value_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dom_actuator_feedback_port_control_state_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_port_control_state_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_port_control_state_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t dom_actuator_feedback_port_actual_throttle_value_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double dom_actuator_feedback_port_actual_throttle_value_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool dom_actuator_feedback_port_actual_throttle_value_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

uint8_t dom_actuator_feedback_port_reserved_2_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_port_reserved_2_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_port_reserved_2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t dom_actuator_feedback_port_danger_fault_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_port_danger_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_port_danger_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_actuator_feedback_port_warning_fault_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_port_warning_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_port_warning_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_actuator_feedback_port_shift_forward_fault_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_port_shift_forward_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_port_shift_forward_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_actuator_feedback_port_shift_neutral_fault_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_port_shift_neutral_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_port_shift_neutral_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_actuator_feedback_port_shift_reverse_fault_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_port_shift_reverse_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_port_shift_reverse_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_actuator_feedback_port_throttle_up_fault_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_port_throttle_up_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_port_throttle_up_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_actuator_feedback_port_throttle_down_fault_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_port_throttle_down_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_port_throttle_down_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t dom_actuator_feedback_port_reserved_3_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_feedback_port_reserved_3_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_feedback_port_reserved_3_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int dom_actuator_cmd_stbd_pack(
    uint8_t *dst_p,
    const struct dom_actuator_cmd_stbd_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->manufacturer_id, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->manufacturer_id, 8u, 0x07u);
    dst_p[1] |= pack_left_shift_u8(src_p->reserved_1, 3u, 0x18u);
    dst_p[1] |= pack_left_shift_u8(src_p->industry_group, 5u, 0xe0u);
    dst_p[2] |= pack_left_shift_u8(src_p->source_instance, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->reserved_2, 4u, 0x30u);
    dst_p[2] |= pack_left_shift_u8(src_p->reserved_3, 6u, 0xc0u);
    dst_p[3] |= pack_left_shift_u8(src_p->gear_command, 0u, 0x0fu);
    dst_p[3] |= pack_left_shift_u8(src_p->reserved_4, 4u, 0xf0u);
    dst_p[4] |= pack_left_shift_u16(src_p->throttle_command, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->throttle_command, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->reserved_5, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->reserved_6, 0u, 0xffu);

    return (8);
}

int dom_actuator_cmd_stbd_unpack(
    struct dom_actuator_cmd_stbd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->manufacturer_id = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->manufacturer_id |= unpack_left_shift_u16(src_p[1], 8u, 0x07u);
    dst_p->reserved_1 = unpack_right_shift_u8(src_p[1], 3u, 0x18u);
    dst_p->industry_group = unpack_right_shift_u8(src_p[1], 5u, 0xe0u);
    dst_p->source_instance = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->reserved_2 = unpack_right_shift_u8(src_p[2], 4u, 0x30u);
    dst_p->reserved_3 = unpack_right_shift_u8(src_p[2], 6u, 0xc0u);
    dst_p->gear_command = unpack_right_shift_u8(src_p[3], 0u, 0x0fu);
    dst_p->reserved_4 = unpack_right_shift_u8(src_p[3], 4u, 0xf0u);
    dst_p->throttle_command = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->throttle_command |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->reserved_5 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->reserved_6 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int dom_actuator_cmd_stbd_init(struct dom_actuator_cmd_stbd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct dom_actuator_cmd_stbd_t));

    return 0;
}

uint16_t dom_actuator_cmd_stbd_manufacturer_id_encode(double value)
{
    return (uint16_t)(value);
}

double dom_actuator_cmd_stbd_manufacturer_id_decode(uint16_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_manufacturer_id_is_in_range(uint16_t value)
{
    return (value <= 2047u);
}

uint8_t dom_actuator_cmd_stbd_reserved_1_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_reserved_1_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_reserved_1_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_cmd_stbd_industry_group_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_industry_group_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_industry_group_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t dom_actuator_cmd_stbd_source_instance_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_source_instance_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_source_instance_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dom_actuator_cmd_stbd_reserved_2_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_reserved_2_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_reserved_2_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_cmd_stbd_reserved_3_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_reserved_3_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_reserved_3_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_cmd_stbd_gear_command_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_gear_command_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_gear_command_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dom_actuator_cmd_stbd_reserved_4_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_reserved_4_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_reserved_4_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t dom_actuator_cmd_stbd_throttle_command_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double dom_actuator_cmd_stbd_throttle_command_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool dom_actuator_cmd_stbd_throttle_command_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

uint8_t dom_actuator_cmd_stbd_reserved_5_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_reserved_5_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_reserved_5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t dom_actuator_cmd_stbd_reserved_6_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_stbd_reserved_6_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_stbd_reserved_6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int dom_actuator_cmd_port_pack(
    uint8_t *dst_p,
    const struct dom_actuator_cmd_port_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->manufacturer_id, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->manufacturer_id, 8u, 0x07u);
    dst_p[1] |= pack_left_shift_u8(src_p->reserved_1, 3u, 0x18u);
    dst_p[1] |= pack_left_shift_u8(src_p->industry_group, 5u, 0xe0u);
    dst_p[2] |= pack_left_shift_u8(src_p->source_instance, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->reserved_2, 4u, 0x30u);
    dst_p[2] |= pack_left_shift_u8(src_p->reserved_3, 6u, 0xc0u);
    dst_p[3] |= pack_left_shift_u8(src_p->gear_command, 0u, 0x0fu);
    dst_p[3] |= pack_left_shift_u8(src_p->reserved_4, 4u, 0xf0u);
    dst_p[4] |= pack_left_shift_u16(src_p->throttle_command, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->throttle_command, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->reserved_5, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->reserved_6, 0u, 0xffu);

    return (8);
}

int dom_actuator_cmd_port_unpack(
    struct dom_actuator_cmd_port_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->manufacturer_id = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->manufacturer_id |= unpack_left_shift_u16(src_p[1], 8u, 0x07u);
    dst_p->reserved_1 = unpack_right_shift_u8(src_p[1], 3u, 0x18u);
    dst_p->industry_group = unpack_right_shift_u8(src_p[1], 5u, 0xe0u);
    dst_p->source_instance = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->reserved_2 = unpack_right_shift_u8(src_p[2], 4u, 0x30u);
    dst_p->reserved_3 = unpack_right_shift_u8(src_p[2], 6u, 0xc0u);
    dst_p->gear_command = unpack_right_shift_u8(src_p[3], 0u, 0x0fu);
    dst_p->reserved_4 = unpack_right_shift_u8(src_p[3], 4u, 0xf0u);
    dst_p->throttle_command = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->throttle_command |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->reserved_5 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->reserved_6 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int dom_actuator_cmd_port_init(struct dom_actuator_cmd_port_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct dom_actuator_cmd_port_t));

    return 0;
}

uint16_t dom_actuator_cmd_port_manufacturer_id_encode(double value)
{
    return (uint16_t)(value);
}

double dom_actuator_cmd_port_manufacturer_id_decode(uint16_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_manufacturer_id_is_in_range(uint16_t value)
{
    return (value <= 2047u);
}

uint8_t dom_actuator_cmd_port_reserved_1_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_reserved_1_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_reserved_1_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_cmd_port_industry_group_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_industry_group_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_industry_group_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t dom_actuator_cmd_port_source_instance_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_source_instance_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_source_instance_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dom_actuator_cmd_port_reserved_2_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_reserved_2_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_reserved_2_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_cmd_port_reserved_3_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_reserved_3_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_reserved_3_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t dom_actuator_cmd_port_gear_command_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_gear_command_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_gear_command_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t dom_actuator_cmd_port_reserved_4_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_reserved_4_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_reserved_4_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t dom_actuator_cmd_port_throttle_command_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double dom_actuator_cmd_port_throttle_command_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool dom_actuator_cmd_port_throttle_command_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

uint8_t dom_actuator_cmd_port_reserved_5_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_reserved_5_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_reserved_5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t dom_actuator_cmd_port_reserved_6_encode(double value)
{
    return (uint8_t)(value);
}

double dom_actuator_cmd_port_reserved_6_decode(uint8_t value)
{
    return ((double)value);
}

bool dom_actuator_cmd_port_reserved_6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
